config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  root "categories#index"

  # Defines the root path route ("/")
  # root "posts#index"
  resources :categories, except: [:edit, :update, :destroy] do
    resource :bookmarks, only: [:new, :create]
  end

  resources :bookmarks, only: [:destroy]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :category
  belongs_to :recipe

  validates :recipe_id, uniqueness: { scope: :category_id }
  validates :comment, length: { minimum: 6, too_short: "must have at least 6 charachters" }
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  has_many :recipes, through: :bookmarks
  has_one_attached :photo

  validates :name, presence: true, uniqueness: true
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  has_many :bookmarks
  has_many :categories

  validates :name, presence: true, uniqueness: true
  validates :description, presence: true
  validates :rating, numericality: { greater_than_or_equal_to: 0, less_than_or_equal_to: 10 }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  def new
    @category = Category.find(params[:category_id])
    @bookmark = Bookmark.new
  end

  def create
    @bookmark = Bookmark.new(bookmark_params)
    @category = Category.find(params[:category_id])
    @bookmark.category = @category
    if @bookmark.save
      redirect_to category_path(@category)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @bookmark = Bookmark.find(params[:id])
    @bookmark.destroy
    redirect_to category_path(@bookmark.category)
  end

  private

  def bookmark_params
    params.require(:bookmark).permit(:comment, :recipe_id)
  end

  end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  # before_action :set_category

def index
@categories = Category.all
end

def show
  @category = Category.find(params[:id])
end

def new
  @category = Category.new
end

def create
  @category = Category.new(category_params)
  if @category.save
    redirect_to categories_path
  else
    render :new,  status: :unprocessable_entity
  end
end


private

def category_params
  params.require(:category).permit(:name, :photo)
end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/bookmarks/new.html.erb
<div class="container mt-4 d-flex justify-content-center ">
  <div class="card-cat">
  <h5>Add a New recipe</h5>
  <%= simple_form_for [@category, @bookmark] do |f| %>
        <div class="form-group">
          <%= f.association :recipe, label: false, input_html: { class: 'form-control' } %>
        </div>
        <div class="form-group">
          <%= f.input :comment,  input_html: { class: 'form-control-file', placeholder: 'Your comment here...' } %>
        </div>

        <%= f.submit 'Add recipe', class: 'btn btn-info mt-3 text-white' %>
  <% end %>

</div>
</div>

app/views/categories/index.html.erb
<%= render "shared/banner" %>

<div class="container mb-4">
  <div class="info-top">
    <h3>List of categories</h3>
    <%= link_to 'New Category', new_category_path, class: "btn btn-warning" %>
  </div>

  <div class="cards">
    <% @categories.each do |category| %>
      <%= link_to category_path(category) do %>
        <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%= cl_image_path category.photo.key, height: 500, crop: :fill %>)">
          <h2><%= category.name %></h2>
        </div>
      <% end %>
    <% end %>

  </div>

</div>

app/views/categories/new.html.erb
<div class="container mt-4 d-flex justify-content-center ">
  <div class="card-cat">
  <h5>Add a New Category</h5>
  <%= simple_form_for @category do |f| %>
        <div class="form-group">
          <%= f.input :name, label: false, input_html: { class: 'form-control', placeholder: 'The category name..' } %>
        </div>
        <div class="form-group">
          <%= f.input :photo, as: :file, label: 'Photo', input_html: { class: 'form-control-file' } %>
        </div>

        <%= f.submit 'Create Category', class: 'btn btn-info mt-3 text-white' %>
  <% end %>

</div>
</div>

app/views/categories/show.html.erb
<div class="container m-4">


<div
  class="banner"
  style="background-image: url('<%= cl_image_path @category.photo.key, height: 300, width: 300, crop: :fill %>');  background-size: cover; background-position: center;">
<div class="banner-text">
<h2><%= @category.name %></h2>
</div>
</div>
<div class="container">
  <div class="info-top">
    <h3>Recipes</h3>
    <%= link_to 'Add a recipe', new_category_bookmarks_path(@category), class: "btn btn-warning" %>
  </div>


<div class="cards">
  <% @category.bookmarks.each do |bookmark| %>
   <div class="card-recipe">

    <%= link_to bookmark_path(bookmark),
       data: { turbo_method: :delete,
               turbo_confirm: "are you sure?" }, class: "btn-delete" do %>
     <i class="fa-solid fa-trash"></i>

     <% end %>
    <img src="<%= bookmark.recipe.image_url%>" alt="recipe image">
    <div class="card-recipe-description">
      <h2><%= bookmark.recipe.name %></h2>
      <p><%= bookmark.recipe.description.truncate(200) %></p>
    </div>
      <br>
    <div class="card-recipe-info">
      <div class="d-flex justify-content-between align-items-center">
       <h2>,,</h2><%=  bookmark.comment %>
      </div>
      <div>
        <%= bookmark.recipe.rating %> <%= '⭐' * bookmark.recipe.rating%>
      </div>
    </div>
   </div>
   <% end %>
</div>
</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsCookbook</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= yield %>
  </body>
</html>

app/views/shared/_banner.html.erb
<div
  class="banner"
  style="background-image: url('https://github.com/moh1384-prg/rails-cookbook/blob/master/app/assets/images/Banner.jpg?raw=true'); height: 300px; background-size: cover; background-position: center;">
<div class="banner-text">
<h1>Cookbook</h1>
<p>Save Your Favourite Recipes</p>
</div>
</div>

app/views/shared/_navbar.html.erb
<div class="nav">
  <%= image_tag "logo.png" %>
  <div class="nav-links">
    <%= link_to "Home", root_path %>
    <%= link_to "New Category", new_category_path %>
  </div>
</div>